let words = [
    { word: "sunflower", hint: "Bright yellow flower that follows the sun" },
    { word: "novel", hint: "Fictional book with an extended narrative" },
    { word: "dance", hint: "Expressive movement of the body in rhythm" },
    { word: "treasure", hint: "Valuable or precious possessions" },
    { word: "laughter", hint: "Expression of amusement or joy" },
    { word: "dream", hint: "Series of thoughts, images, or emotions occurring during sleep" },
    { word: "victory", hint: "Success in a battle, game, or competition" },
    { word: "magic", hint: "Supernatural or mystical power" },
    { word: "journey", hint: "Travel from one place to another" },
    { word: "fireworks", hint: "Bursts of light and sound in the sky for celebration" },
    { word: "mystery", hint: "Something that is difficult or impossible to understand or explain" },
    { word: "adventure", hint: "Exciting or unusual experience" },
    { word: "courage", hint: "Ability to confront fear or adversity" },
    { word: "creativity", hint: "Ability to produce or use original and imaginative ideas" },
    { word: "harmony", hint: "Agreement or concord" },
    { word: "serenity", hint: "State of being calm, peaceful, and untroubled" },
    { word: "butterfly", hint: "Insect with brightly colored wings" },
    { word: "oasis", hint: "Fertile spot in a desert where water is found" },
    { word: "storybook", hint: "Collection of stories, often for children" },
    { word: "sparkle", hint: "Shine brightly with flashes of light" },
    { word: "brilliance", hint: "Intense brightness of light" },
    { word: "whisper", hint: "Speak very softly using one's breath rather than one's throat" },
    { word: "tranquility", hint: "Quality or state of being tranquil; calmness; peacefulness; quiet; serenity" },
    { word: "ethereal", hint: "Extremely delicate and light in a way that seems too perfect for this world" },
    { word: "puzzle", hint: "Game, toy, or problem designed to test ingenuity or knowledge" },
    { word: "bicycle", hint: "Vehicle with two wheels and pedals that is propelled by foot" },
    { word: "mountain", hint: "Massive natural elevation of earth's surface" },
    { word: "adventure", hint: "Exciting or unusual experience" },
    { word: "technology", hint: "Application of scientific knowledge" },
    { word: "rainbow", hint: "Meteorological phenomenon" },
    { word: "music", hint: "Art form consisting of sound and silence" },
    { word: "island", hint: "Landmass surrounded by water" },
    { word: "education", hint: "Process of acquiring knowledge and skills" },
    { word: "journey", hint: "Travel from one place to another" },
    { word: "creativity", hint: "Ability to generate new ideas" },
    { word: "harmony", hint: "Agreement in action or opinion" },
    { word: "innovation", hint: "Introduction of something new" },
    { word: "vision", hint: "Ability to see" },
    { word: "hope", hint: "Optimistic attitude of expectation" },
    { word: "reflection", hint: "Serious thought or consideration" },
    { word: "celebration", hint: "Festive observance or ceremony" },
    { word: "discovery", hint: "Finding or uncovering something previously unknown" },
    { word: "efficiency", hint: "Ability to accomplish a task with minimal waste" },
    { word: "imagination", hint: "Faculty of forming new ideas" },
    { word: "ocean", hint: "Vast body of saltwater" },
    { word: "unity", hint: "State of being united or joined as a whole" },
    { word: "community", hint: "Group of people living in the same area" },
    { word: "history", hint: "Study of past events" },
    { word: "knowledge", hint: "Facts, information, and skills acquired through experience or education" },
    { word: "wisdom", hint: "Quality of having experience, knowledge, and good judgment" },
    { word: "courage", hint: "Ability to confront fear or adversity" },
    { word: "peace", hint: "State of tranquility or harmony" },
    { word: "nature", hint: "Physical world and its phenomena" },
    { word: "connection", hint: "Link or relationship between people or things" },
    { word: "passion", hint: "Strong and intense emotion or enthusiasm" },
    { word: "gratitude", hint: "Thankfulness and appreciation" },
    { word: "balance", hint: "State of equilibrium or stability" },
    { word: "friendship", hint: "Mutual affection and trust between individuals" },
    { word: "inspiration", hint: "Stimulation of the mind or emotions to creative thought or action" },
    { word: "resilience", hint: "Capacity to recover quickly from difficulties" },
    { word: "diversity", hint: "Range and variety of different things" },
    { word: "kindness", hint: "Quality of being friendly, generous, and considerate" },
    { word: "beauty", hint: "Quality that gives pleasure to the senses or pleasurably exalts the mind or spirit" },
    { word: "freedom", hint: "State of being free from oppression or restraint" },
    { word: "laughter", hint: "Expression of mirth, amusement, or joy" },
    { word: "curiosity", hint: "Desire to learn or know about anything" },
    { word: "leadership", hint: "Action of leading a group or organization" },
    { word: "empathy", hint: "Ability to understand and share the feelings of others" },
    { word: "empowerment", hint: "Authority or power given to someone to do something" },
    { word: "happiness", hint: "State of being happy" },
    { word: "simplicity", hint: "Quality or condition of being simple" },
    { word: "synergy", hint: "Interaction of elements that when combined produce a total effect that is greater than the sum of the individual elements" },
    { word: "bliss", hint: "State of perfect happiness or joy" },
    { word: "cascade", hint: "Waterfall or series of small waterfalls over rocks" },
    { word: "breeze", hint: "Gentle wind" },
    { word: "serenity", hint: "State of being calm, peaceful, and untroubled" },
    { word: "melody", hint: "Succession of musical notes forming a distinctive sequence" },
    { word: "triumph", hint: "Great victory or achievement" },
    { word: "inspiration", hint: "Stimulation of the mind or emotions to creative thought or action" },
    { word: "serendipity", hint: "The occurrence of events by chance in a happy or beneficial way" },
    { word: "optimism", hint: "Hopefulness and confidence about the future or the success of something" },
    { word: "glisten", hint: "Shine with a sparkling light" },
    { word: "cozy", hint: "Giving a feeling of comfort, warmth, and relaxation" },
    { word: "giggle", hint: "Laugh lightly in a nervous, affected, or silly manner" },
    { word: "lullaby", hint: "Soft, soothing song sung to children before they go to sleep" },
    { word: "paradise", hint: "Place or state of bliss, felicity, or delight" },
    { word: "sunshine", hint: "Direct sunlight unobscured by cloud" },
    { word: "flutter", hint: "Wave or flap rapidly in an irregular manner" },
    { word: "tranquility", hint: "Quality or state of being tranquil; calmness; peacefulness; quiet; serenity" },
    { word: "whimsical", hint: "Playfully quaint or fanciful, especially in an appealing and amusing way" },
    { word: "savor", hint: "Enjoy with great delight, relish, or taste" },
    { word: "glow", hint: "Give out steady light from a bright source" },
    { word: "twinkle", hint: "Shine with a flickering or sparkling light" },
    { word: "luminous", hint: "Radiating or reflecting light; shining; bright" },
    { word: "lively", hint: "Full of life and energy; active and outgoing" },
    { word: "enchanted", hint: "Filled with great delight, captivated, charmed, or under a spell" },
    { word: "glimmer", hint: "Shine faintly with a wavering light" },
    { word: "ethereal", hint: "Extremely delicate and light in a way that seems too perfect for this world" },
    { word: "bubbly", hint: "Full of cheerful high spirits; effervescent; lively; animated" },
    { word: "radiant", hint: "Sending out light; shining or glowing brightly" },
    { word: "mystical", hint: "Relating to or resembling mysticism; mysterious" },
    { word: "harmonious", hint: "Forming a pleasing or consistent whole" },
    { word: "sprinkle", hint: "Scatter or distribute (something) here and there" },
    { word: "joyful", hint: "Feeling, expressing, or causing great pleasure and happiness" },
    { word: "lucid", hint: "Clear, easy to understand; showing ability to think clearly, especially in intervals between periods of confusion or insanity" },
    { word: "twilight", hint: "Soft, diffused light occurring when the sun is just below the horizon" },
    { word: "effervescent", hint: "Giving off bubbles; fizzy; vivacious and enthusiastic" },
    { word: "breeze", hint: "Gentle wind" },
    { word: "flourish", hint: "Grow or develop in a healthy or vigorous way, especially as the result of a particularly favorable environment" },
    { word: "crisp", hint: "Crackling, brittle, or crunchy; fresh and invigorating" },
    { word: "serene", hint: "Calm, peaceful, and untroubled; tranquil" },
    { word: "iridescent", hint: "Showing luminous colors that seem to change when seen from different angles" },
    { word: "flicker", hint: "Shine unsteadily; flutter rapidly" },
    { word: "buoyant", hint: "Able or apt to stay afloat or rise to the top of a liquid or gas; cheerful and optimistic" },
    { word: "purity", hint: "Freedom from adulteration or contamination; freedom from immorality, especially of a sexual nature" },
    { word: "soothing", hint: "Having a gently calming effect" },
    { word: "vibrant", hint: "Full of energy and enthusiasm; bright and striking" },
    { word: "whisper", hint: "Speak very softly using one's breath rather than one's throat" },
    { word: "cascade", hint: "Waterfall or series of small waterfalls over rocks" },
    { word: "breeze", hint: "Gentle wind" },
    { word: "serenity", hint: "State of being calm, peaceful, and untroubled" },
    { word: "melody", hint: "Succession of musical notes forming a distinctive sequence" },
    { word: "triumph", hint: "Great victory or achievement" },
    { word: "inspiration", hint: "Stimulation of the mind or emotions to creative thought or action" },
    { word: "serendipity", hint: "The occurrence of events by chance in a happy or beneficial way" },
    { word: "optimism", hint: "Hopefulness and confidence about the future or the success of something" },
    { word: "glisten", hint: "Shine with a sparkling light" },
    { word: "cozy", hint: "Giving a feeling of comfort, warmth, and relaxation" },
    { word: "giggle", hint: "Laugh lightly in a nervous, affected, or silly manner" },
    { word: "lullaby", hint: "Soft, soothing song sung to children before they go to sleep" },
    { word: "paradise", hint: "Place or state of bliss, felicity, or delight" },
    { word: "sunshine", hint: "Direct sunlight unobscured by cloud" },
    { word: "flutter", hint: "Wave or flap rapidly in an irregular manner" },
    { word: "tranquility", hint: "Quality or state of being tranquil; calmness; peacefulness; quiet; serenity" },
    { word: "whimsical", hint: "Playfully quaint or fanciful, especially in an appealing and amusing way" },
    { word: "savor", hint: "Enjoy with great delight, relish, or taste" },
    { word: "glow", hint: "Give out steady light from a bright source" },
    { word: "twinkle", hint: "Shine with a flickering or sparkling light" },
    { word: "luminous", hint: "Radiating or reflecting light; shining; bright" },
    { word: "lively", hint: "Full of life and energy; active and outgoing" },
    { word: "enchanted", hint: "Filled with great delight, captivated, charmed, or under a spell" },
    { word: "glimmer", hint: "Shine faintly with a wavering light" },
    { word: "ethereal", hint: "Extremely delicate and light in a way that seems too perfect for this world" },
    { word: "bubbly", hint: "Full of cheerful high spirits; effervescent; lively; animated" },
    { word: "radiant", hint: "Sending out light; shining or glowing brightly" },
    { word: "mystical", hint: "Relating to or resembling mysticism; mysterious" },
    { word: "harmonious", hint: "Forming a pleasing or consistent whole" },
    { word: "sprinkle", hint: "Scatter or distribute (something) here and there" },
    { word: "joyful", hint: "Feeling, expressing, or causing great pleasure and happiness" },
    { word: "lucid", hint: "Clear, easy to understand; showing ability to think clearly, especially in intervals between periods of confusion or insanity" },
    { word: "twilight", hint: "Soft, diffused light occurring when the sun is just below the horizon" },
    { word: "effervescent", hint: "Giving off bubbles; fizzy; vivacious and enthusiastic" },
    { word: "breeze", hint: "Gentle wind" },
    { word: "flourish", hint: "Grow or develop in a healthy or vigorous way, especially as the result of a particularly favorable environment" },
    { word: "crisp", hint: "Crackling, brittle, or crunchy; fresh and invigorating" },
    { word: "serene", hint: "Calm, peaceful, and untroubled; tranquil" },
    { word: "iridescent", hint: "Showing luminous colors that seem to change when seen from different angles" },
    { word: "flicker", hint: "Shine unsteadily; flutter rapidly" },
    { word: "buoyant", hint: "Able or apt to stay afloat or rise to the top of a liquid or gas; cheerful and optimistic" },
    { word: "purity", hint: "Freedom from adulteration or contamination; freedom from immorality, especially of a sexual nature" },
    { word: "soothing", hint: "Having a gently calming effect" },
    { word: "vibrant", hint: "Full of energy and enthusiasm; bright and striking" },
    { word: "whisper", hint: "Speak very softly using one's breath rather than one's throat" },
    { word: "addition", hint: "The process of adding numbers" },
    { word: "meeting", hint: "Event in which people come together" },
    { word: "number", hint: "Math symbol used for counting" },
    { word: "exchange", hint: "The act of trading" },
    { word: "canvas", hint: "Piece of fabric for oil painting" },
    { word: "garden", hint: "Space for planting flower and plant" },
    { word: "position", hint: "Location of someone or something" },
    { word: "feather", hint: "Hair like outer covering of bird" },
    { word: "comfort", hint: "A pleasant feeling of relaxation" },
    { word: "tongue", hint: "The muscular organ of mouth" },
    { word: "expansion", hint: "The process of increase or grow" },
    { word: "country", hint: "A politically identified region" },
    { word: "group", hint: "A number of objects or persons" },
    { word: "taste", hint: "Ability of tongue to detect flavour" },
    { word: "store", hint: "Large shop where goods are traded" },
    { word: "field", hint: "Area of land for farming activities" },
    { word: "friend", hint: "Person other than a family member" },
    { word: "pocket", hint: "A bag for carrying small items" },
    { word: "needle", hint: "A thin and sharp metal pin" },
    { word: "expert", hint: "Person with extensive knowledge" },
    { word: "statement", hint: "A declaration of something" },
    { word: "second", hint: "One-sixtieth of a minute" },
    { word: "library", hint: "Place containing collection of books" }
];
